routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});

//Route::view('signup' , 'admin/signup');
//Route::view('register' , 'register');

Auth::routes();
//Route::resource('admin' , 'AdminController');


Route::view('addauthor' , 'author/addAuthor');
Route::resource('lms' , 'ResourceController');


Route::resource('book' , 'BookController');



Route::get('/home', 'HomeController@index')->name('home');

app/Book.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Book extends Model
{
    public function author()
    {
        return $this->belongsTo('App\Author');
    }

    protected $guarded = [];
    protected $table = 'books';
}

app/Http/Controllers/BookController.php
<?php

namespace App\Http\Controllers;

use App\Author;
use App\Book;
use App\Http\Requests\Book\bookRequest;
use App\Http\Requests\Book\StoreBookRequest;
use Illuminate\Http\Request;

class BookController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $books = Book::with('author')->get();
//        dd($books);
//        $book = Book::all();
//        echo $book->author->fname;
//        dd($books[0]->author->fname);


        return view('book/displayBook')->with('books' , $books);

//        return view('book/displayBook');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $authors = Author::all();

        return view('book/addBook')->with('authors' , $authors);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(bookRequest $request)
    {
        $book = new Book;
      //  $validatedData = $request->validate([
       //     'title' => 'required|max:100',
       //     'pages' => 'required|numeric',
      //      'description' => 'required',
       // ],
       //     [
       //         'title.required' => ' Title is req',
       //         'title.max' => ' Title is req'

       //     ]);

        $book->title = $request->title;
        $book->pages = $request->pages;
        $book->author_id = $request->select;
        $book->book_description = $request->description;

        $book->save();

        if ($book->save())
        {
            // echo "Book Inserted Successfully";
           return redirect()->action('BookController@index');
        }
        else{
            echo "Insertion failed";
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {

        $book = Book::find($id);
//        $author = Book::find($id)->author;

        return view('book/showBook')->with('book' , $book);




//        $book = Author::find($id)->book;
//        echo count($book). " Records found <br>";
//        echo $book;

        $author = Book::find($id)->author;
        echo $author;
//        echo count($author). " Records found <br>";


    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $book = Book::find($id);
        $authors = Author::all();
        return view('book/editBook')->with('book' , $book)->with('authors' , $authors);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(bookRequest $request, $id)
    {
        $book = Book::find($id);
        $book->title = $request->title;
        $book->pages = $request->pages;
        $book->book_description = $request->description;
        $book->author_id = $request->select;
        $book->save();

        return redirect()->action('BookController@index');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
//        dd($request->all());
        $book = Book::find($id);
        $book->delete();

        return redirect()->action('BookController@create');


    }
}

resources/views/book/addBook.blade.php
@extends('html')

@section('js')
  <!-- Theme JS files -->
  <script type="text/javascript" src="{{ asset('assets/js/core/libraries/jquery_ui/core.min.js') }}"></script>

  <script type="text/javascript" src="{{asset('assets/js/plugins/forms/styling/uniform.min.js')}}"></script>
  <script type="text/javascript" src="{{ asset('assets/js/pages/form_selectbox.js')}}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/plugins/forms/selects/selectboxit.min.js') }}"></script>
    <script type="text/javascript" src="{{asset('assets/js/plugins/ui/ripple.min.js')}}"></script>
  <!-- <script type="text/javascript" src="assets/js/core/app.js"></script> -->

  <!-- <script type="text/javascript" src="{{asset('assets/js/plugins/forms/selects/select2.min.js')}}"></script> -->

    <!-- <script type="text/javascript" src="{{asset('assets/js/pages/form_layouts.js')}}"></script> -->

	<!-- <script type="text/javascript" src="assets/js/core/libraries/jquery_ui/core.min.js"></script>
	<script type="text/javascript" src="assets/js/plugins/forms/selects/selectboxit.min.js"></script>
	<script type="text/javascript" src="assets/js/pages/form_selectbox.js"></script> -->
    <!-- /theme JS files -->


@endsection

@section('content')

<div class="row">
            <div class="col-md-8">

                <!-- Basic legend -->
                <form class="form-horizontal" action="/book" method="POST" id="">
                @csrf
                    <div class="panel panel-flat">

                        <div class="panel-body">
                            <fieldset>
                                <legend class="text-semibold">Add New Book</legend>

                                <div class="form-group">
                                    <label class="col-lg-3 control-label">Titile:</label>
                                    <div class="col-lg-9">
                                        <input type="text" class="form-control" name="title" placeholder="Enter Title">
                                    <div style="color: red"> @error('title')
                                        {{$message}}
                                        @enderror
                                    </div>
                                    </div>

                                </div>
                                <div class="form-group">
                                    <label class="col-lg-3 control-label">Pages:</label>
                                    <div class="col-lg-9">
                                        <input type="text" class="form-control" name="pages" placeholder="Pages of book">
                                    <div style="color: red"> @error('pages')
                                        {{$message}}
                                        @enderror
                                    </div>
                                    </div>

                                </div>


                                <!-- Default select -->
									<!-- <div class="form-group">
										<label>Default select</label>
										<select class="selectbox">
											<option value="AK">Alaska</option>
											<option value="HI">Hawaii</option>
											<option value="CA">California</option>
											<option value="NV">Nevada</option>
											<option value="OR">Oregon</option>
										</select>
									</div> -->
									<!-- /default select -->


                                <div class="form-group ">
                                    <label for="" class="col-lg-3 control-label">Author</label>
                                    <div class="col-lg-9">

                                            <select name="select" class="selectbox form-control">
                                                <option value="#">Select Author</option>
                                                @foreach ($authors as  $author)
                                                    <option value="{{ $author->id }}">{{ $author->fname}}</option>
                                                @endforeach
                                            </select>
                                    <div style="color: red"> @error('select')
                                        {{$message}}
                                        @enderror
                                    </div>
                                    </div>

                                </div>


                                <div class="form-group">
                                    <label class="col-lg-3 control-label">Book Description:</label>
                                    <div class="col-lg-9">
                                        <textarea rows="5" cols="5" name="description" class="form-control" placeholder="Enter Description"></textarea>
                                    <div style="color: red"> @error('description')
                                        {{$message}}
                                        @enderror
                                    </div>
                                    </div>

                                </div>
                            </fieldset>

                            <div class="text-right">
                                <button type="submit" class="btn btn-primary">Add Book <i class="icon-arrow-right14 position-right"></i></button>
                            </div>
                        </div>
                    </div>
                </form>
                <!-- /basic legend -->

            </div>
        </div>




<!--
<form action="/book" method="POST">
    @csrf

    <div class="container mt-5">
        <h2>Insert Book Details</h2>
        <div class="form-group row mt-5 ">
            <label for="" class="col-sm-2 col-form-label">Title</label>
            <div class="col-sm-4">
                <input type="text" class="form-control" name="title" placeholder="Title">
            </div>
            <div style="color: red"> @error('title')
                {{$message}}
                @enderror
            </div>
        </div>



        <div class="form-group row">
            <label for="" class="col-sm-2 col-form-label">Pages</label>
            <div class="col-sm-4">
                <input type="number" class="form-control" name="pages" placeholder="Pages">
            </div>
            <div style="color: red"> @error('pages')
                {{$message}}
                @enderror
            </div>
        </div>


        <div class="form-group row">
            <label for="" class="col-sm-2 col-form-label">Author</label>
            <div class="col-sm-4">

                    <select name="select" class="form-control">
                        <option value="#">Select Author</option>
                        @foreach ($authors as  $author)
                            <option value="{{ $author->id }}">{{ $author->fname}}</option>
                        @endforeach
                    </select>
            </div>
            <div style="color: red"> @error('select')
                {{$message}}
                @enderror
            </div>
        </div>



        <div class="form-group row">
            <label for="" class="col-sm-2 col-form-label">Description</label>
            <div class="col-sm-4">
        <textarea name="description" class="form-control" id="" cols="30" rows="8" placeholder="Description"
        ></textarea>
            </div>
            <div style="color: red"> @error('description')
                {{$message}}
                @enderror
            </div>
        </div>


        <div class="form-group row">
            <div class="col-sm-10 ">
                <button type="submit" class="btn btn-primary">Add Book</button>
            </div>
        </div>


    </div> -->

</form>
    @endsection

resources/views/book/displayBook.blade.php
@extends('html')
@section('js')
{{--    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>--}}

    <script type="text/javascript" src="{{ asset('assets/js/plugins/buttons/ladda.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/pages/components_buttons.js') }}"></script>




@endsection
@section('title' , 'Display Book')


{{--@foreach($books as $book)--}}

{{--@endforeach--}}

@section('content')

    <table class="table datatable-basic mt-5">
        <thead>
        <tr>
            <th scope="col">Title</th>
            <th scope="col">Author Name</th>
            <th scope="col">Pages</th>
            <th scope="col">Description</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody>

        @foreach($books as $book)
            <tr>
                <input type="text" id="$book->id" hidden value="{{$book->id}}">
{{--                <label for=""  id="book_id" >{{$book->id}}</label>--}}
                <td>{{ $book->title }}</td>
                <td>{{ $book->author->fname." ".$book->author->lname }}</td>
                <td>{{ $book->pages }}</td>
                <td>{{ $book->book_description }}</td>
                <td>
                    {{--                    <form action="/book/{{$book->id}}" method="post">--}}
                    {{--                        @csrf--}}
                    {{--                        @method('DELETE')--}}
                    {{--                        <a href="/book/{{$book->id}}/edit"><i class="fas fa-edit mx-2"> </i> </a>--}}
                    {{--                        <button class="border-0 ml-2" type="submit" name="delete"><i class="fas fa-trash-alt"></i></button>--}}
                    {{--                        <a href="/book/{{$book->id}}"><i class="far ml-2 fa-eye"></i></a>--}}
                    {{--                    </form>--}}

                    <a href="/book/{{$book->id}}/edit"><i class="fas fa-edit mx-2"> </i> </a>
                    <a href=""  class="border-0 ml-2 deleteBtn" data-id="{{ $book->id }}" name="delete"><i class="fas fa-trash  mx-2"> </i> </a>
{{--                    <button class="border-0 ml-2 deleteBtn" data-id="{{ $book->id }}" name="delete"><i class="fas fa-trash-alt"></i></button>--}}
                    <a href="/book/{{$book->id}}"> <i class="far ml-2 fa-eye"></i></a>

                </td>
            </tr>
        @endforeach
        </tbody>
    </table>

    <b> {{ $books->count() . " Records Found"}}</b>
    <form action="/book/create" class="text-center">
        @csrf
        <button type="submit" class=" btn btn-primary btn-lg text-center">Add New Book</button>
    </form>

@endsection

<script src="{{asset('js/jquery.js')}}"></script>
<script type="text/javascript" >

    $(document).ready(function(){
        $(".deleteBtn").click(function(){
            // alert('hello');
            let bookId = $(this).attr('data-id');

            var url = "{{ route('book.destroy' , ['book' => ':bookId'])}}";
             url = url.replace(':bookId', bookId);
console.log('------',url);
            console.log(bookId);
            $.ajax({
                type:'POST',
                data:{_method: 'delete',_token : '{{ csrf_token() }}' },
                // method: "DELETE",
                {{--                    url: "{{ url('/book/{$book->id}') }}",--}}
                url: url,

                success: function() {
                    window.location.href = "{{ route('book.index')}}";


                }


            });
        });
    });
</script>

resources/views/book/editBook.blade.php
@extends('html')

@section('js')
    <script type="text/javascript" src="{{ asset('assets/js/core/libraries/jquery_ui/core.min.js') }}"></script>
	<script type="text/javascript" src="{{ asset('assets/js/pages/form_selectbox.js')}}"></script>
    <script type="text/javascript" src="{{ asset('assets/js/plugins/forms/selects/selectboxit.min.js') }}"></script>
	<script type="text/javascript" src="{{ asset('assets/js/plugins/ui/ripple.min.js')}}"></script>

@endsection

@section('content')


<div class="row">
            <div class="col-md-8">

                <!-- Basic legend -->
                <form class="form-horizontal" action="/book/{{$book->id}}" method="POST" id="">
                @csrf
                @method('PUT')
                    <div class="panel panel-flat">

                        <div class="panel-body">
                            <fieldset>
                                <legend class="text-semibold">Update Book</legend>

                                <div class="form-group">
                                    <label class="col-lg-3 control-label">Titile:</label>
                                    <div class="col-lg-9">
                                        <input type="text" class="form-control" name="title" value="{{$book->title}}">
                                    </div>
                                    <div style="color: red"> @error('title')
                                        {{$message}}
                                        @enderror
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-lg-3 control-label">Pages:</label>
                                    <div class="col-lg-9">
                                        <input type="text" class="form-control" name="pages" value="{{$book->pages}}">
                                    </div>
                                    <div style="color: red"> @error('pages')
                                        {{$message}}
                                        @enderror
                                    </div>
                                </div>

                                <div class="form-group ">
                                    <label for="" class="col-lg-3 control-label">Author</label>
                                    <div class="col-lg-9">

                                            <select name="select" class="selectbox form-control">
                                                <!-- <option value="#">Select Author</option> -->
                                                @foreach ($authors as  $author)
                                                    <option value="{{ $author->id }}" {{$book->author_id == $author->id ? "selected" : "" }}>{{ $author->fname}}</option>
                                                @endforeach
                                            </select>
                                    </div>
                                    <div style="color: red"> @error('select')
                                        {{$message}}
                                        @enderror
                                    </div>
                                </div>


                                <div class="form-group">
                                    <label class="col-lg-3 control-label">Book Description:</label>
                                    <div class="col-lg-9">
                                        <textarea rows="5" cols="5" name="description" class="form-control" >{{$book->book_description}}</textarea>
                                    </div>
                                    <div style="color: red"> @error('description')
                                        {{$message}}
                                        @enderror
                                    </div>
                                </div>
                            </fieldset>

                            <div class="text-right">
                                <button type="submit" class="btn btn-primary">Update Book <i class="icon-arrow-right14 position-right"></i></button>
                            </div>
                        </div>
                    </div>
                </form>
                <!-- /basic legend -->

            </div>
        </div>

<!--
<form action="/book/{{$book->id}}" method="POST">
    @csrf
    @method('PATCH')


    <div class="container mt-5">
        <h2>Insert Book Details</h2>
        <div class="form-group row mt-5 ">
            <label for="" class="col-sm-2 col-form-label">Title</label>
            <div class="col-sm-4">
                <input type="text" class="form-control" name="title" placeholder="Title" value="{{$book->title}}">
            </div>
            <div style="color: red"> @error('title')
                {{$message}}
                @enderror
            </div>
        </div>



        <div class="form-group row">
            <label for="" class="col-sm-2 col-form-label">Pages</label>
            <div class="col-sm-4">
                <input type="number" class="form-control" name="pages" placeholder="Pages" value="{{$book->pages}}">
            </div>
            <div style="color: red"> @error('pages')
                {{$message}}
                @enderror
            </div>
        </div>


        <div class="form-group row">
            <label for="" class="col-sm-2 col-form-label">Author</label>
            <div class="col-sm-4">

                <select name="select" class="form-control">
                    <option value="#">Select Author</option>
                    @foreach ($authors as  $author)
                        <option value="{{ $author->id }}" {{$book->author_id == $author->id ? "selected" : "" }} >{{ $author->fname}}</option>
                    @endforeach
                </select>


            </div>
            <div style="color: red"> @error('select')
                {{$message}}
                @enderror
            </div>
        </div>



        <div class="form-group row">
            <label for="" class="col-sm-2 col-form-label">Description</label>
            <div class="col-sm-4">
        <textarea name="description" class="form-control" id="" cols="30" rows="8" placeholder="Description"
        >{{$book->book_description}}</textarea>
            </div>
            <div style="color: red"> @error('description')
                {{$message}}
                @enderror
            </div>
        </div>


        <div class="form-group row">
            <div class="col-sm-10 ">
                <button type="submit" class="btn btn-primary">Add Book</button>
            </div>
        </div>


    </div>

</form> -->
@endsection

resources/views/book/showBook.blade.php
@include('html')


<form action="">
    <h3>Show Book</h3>
</form>

<form action="" method="GET" class="mt-5" >

    <table class="table table-bordered table-dark">
        <thead>
        <tr>

            <th scope="col">Title</th>
            <th scope="col">Author Name</th>
            <th scope="col">Pages</th>
            <th scope="col">Description</th>
        </tr>
        </thead>
        <tbody>
        <tr>

            <td>{{$book->title}}</td>
            <td> {{$book->author->fname ." " . $book->author->lname}}</td>
            <td>{{$book->pages}}</td>
            <td>{{$book->book_description}}</td>

        </tr>

        </tbody>
    </table>

</form>