routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});

//Route::view('signup' , 'admin/signup');
//Route::view('register' , 'register');

Auth::routes();
//Route::resource('admin' , 'AdminController');


Route::view('addauthor' , 'author/addAuthor');
Route::resource('lms' , 'ResourceController');


Route::resource('book' , 'BookController');



Route::get('/home', 'HomeController@index')->name('home');

app/Author.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Author extends Model
{
    public function book()
    {
        return $this->hasMany('App\Book' , 'author_id' , 'id');
    }

    protected $guarded = [];
    protected $table = 'authors';
}

resources/views/author/addAuthor.blade.php
@extends('html')

@section('js')
<!-- Theme JS files -->
<!-- <script type="text/javascript" src="{{asset('assets/js/plugins/forms/selects/select2.min.js')}}"></script> -->
<script type="text/javascript" src="{{asset('assets/js/plugins/forms/styling/uniform.min.js')}}"></script>

<!-- <script type="text/javascript" src="{{asset('assets/js/core/app.js')}}"></script> -->
<!-- <script type="text/javascript" src="{{asset('assets/js/pages/form_layouts.js')}}"></script> -->

<script type="text/javascript" src="{{asset('assets/js/plugins/ui/ripple.min.js')}}"></script>
{{--    <!-- /theme JS files -->--}}
<!-- Theme JS files -->
<script type="text/javascript" src="{{ asset('assets/js/plugins/notifications/jgrowl.min.js') }} "></script>
<script type="text/javascript" src="{{ asset('assets/js/plugins/ui/moment/moment.min.js') }}"></script>


<script type="text/javascript" src="{{ asset('assets/js/plugins/ui/ripple.min.js') }}"></script>
<!-- /theme JS files -->

<!-- ajax  -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
<!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" /> -->
<script src="https://cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.12/js/dataTables.bootstrap.min.js"></script>
<link rel="stylesheet" href="https://cdn.datatables.net/1.10.12/css/dataTables.bootstrap.min.css" />
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
@endsection
@section('title' , 'Add Author')
@section('content')


<div class="row">
    <div class="col-md-8">

        <!-- Basic legend -->
        <form class="form-horizontal" action="/lms" method="POST" id="addAuthor">
            @csrf
            <div class="panel panel-flat">
                <div class="panel-heading">
                    <h5 class="panel-title">Add New Author</h5>

                </div>

                <div class="panel-body">
                    <fieldset>


                        <div class="form-group">
                            <label class="col-lg-3 control-label">First Name:</label>
                            <div class="col-lg-9">
                                <input type="text" class="form-control" name="fname" placeholder="First Name">
                                <div style="color: red"> @error('fname')
                                    {{$message}}
                                    @enderror
                                </div>
                            </div>

                        </div>
                        <div class="form-group">
                            <label class="col-lg-3 control-label">Last Name:</label>
                            <div class="col-lg-9">
                                <input type="text" class="form-control" name="lname" placeholder="Last Name">
                                <div style="color: red"> @error('lname')
                                    {{$message}}
                                    @enderror
                                </div>
                            </div>

                        </div>

                        <div class="form-group">
                            <label class="control-label col-lg-3">Date</label>
                            <div class="col-lg-9">
                                <input class="form-control" type="date" name="dob">
                                <div style="color: red"> @error('dob')
                                    {{$message}}
                                    @enderror
                                </div>
                            </div>

                        </div>

                        <!-- <div class="form-group ">
                                    <label class="col-lg-3 control-label">Date Of Birth</label>
                                    <div class="col-lg-9">
                                        <input type="text" class="form-control pickadate" name="dob" placeholder="Enter your Birthdate&hellip;">
                                    </div>
                                </div> -->

                        <div class="form-group">
                            <label class="col-lg-3 control-label">Gender:</label>
                            <div class="col-lg-9">
                                <label class="radio-inline">
                                    <input type="radio" name="gender" value="Male" class="styled" checked="checked">
                                    Male
                                </label>

                                <label class="radio-inline">
                                    <input type="radio" name="gender" value="Female" class="styled">Female</label>
                                <div style="color: red"> @error('gender')
                                    {{$message}}
                                    @enderror
                                </div>
                            </div>

                        </div>
                        <div class="form-group">
                            <label class="col-lg-3 control-label">Contact Number:</label>
                            <div class="col-lg-9">
                                <input type="text" class="form-control" name="mobile" placeholder="Contact Number">
                                <div style="color: red"> @error('mobile')
                                    {{$message}}
                                    @enderror
                                </div>
                            </div>

                        </div>
                        <div class="form-group">
                            <label class="col-lg-3 control-label">Author Description:</label>
                            <div class="col-lg-9">
                                <textarea rows="5" cols="5" name="description" class="form-control"
                                    placeholder="Enter your message here"></textarea>
                                <div style="color: red"> @error('description')
                                    {{$message}}
                                    @enderror
                                </div>
                            </div>

                        </div>
                    </fieldset>

                    <div class="text-right">
                        <button type="submit" class="btn btn-primary">Add Author <i
                                class="icon-arrow-right14 position-right"></i></button>
                    </div>
                </div>
            </div>
        </form>
        <!-- /basic legend -->

    </div>
</div>

<!-- 
        <form action="/lms" method="POST" id="addAuthor">
    @csrf

    <div class="container mt-5">
        <h2>Insert Author Details</h2>
        <div class="form-group row mt-5 ">
            <label for="fname" class="col-sm-2 col-form-label">First Name</label>
            <div class="col-sm-4">
                <input type="text" class="form-control" name="fname" id="fname" placeholder="First Name" email>
            </div>
            <div style="color: red"> @error('fname')
                {{$message}}
                @enderror
            </div>
        </div>

        <div class="form-group row">
            <label for="lname" class="col-sm-2 col-form-label">Last Name</label>
            <div class="col-sm-4">
                <input type="text" class="form-control" name="lname" placeholder="Last Name">
            </div>
            <div style="color: red"> @error('lname')
                {{$message}}
                @enderror
            </div>
        </div>

        <div class="form-group row">
            <label for="dob" class="col-sm-2 col-form-label">DOB</label>
            <div class="col-sm-4">
                <input type="date" class="form-control" name="dob" placeholder="Last Name">
            </div>
            <div style="color: red"> @error('dob')
                {{$message}}
                @enderror
            </div>
        </div>


        <div class="form-group row">
            <label for="gender" class="col-sm-2 col-form-label">Gender</label>
            <div class="col-sm-4">
                <input type="radio" name="gender"  value="Male"> Male
                <input type="radio" name="gender"  value="Female"> Female
            </div>
            <div style="color: red"> @error('gender')
                {{$message}}
                @enderror
            </div>
        </div>

        <div class="form-group row">
            <label for="mobile" class="col-sm-2 col-form-label">Mobile</label>
            <div class="col-sm-4">
                <input type="text" class="form-control" id="mobile" name="mobile" placeholder="Contact Number">
            </div>
            <div style="color: red"> @error('mobile')
                {{$message}}
                @enderror
            </div>
        </div>


        <div class="form-group row">
            <label for="description" class="col-sm-2 col-form-label">Description</label>
            <div class="col-sm-4">
        <textarea name="description" class="form-control" id="" cols="30" rows="8"
        ></textarea>
            </div>
            <div style="color: red"> @error('description')
                {{$message}}
                @enderror
            </div>
        </div>


        <div class="form-group row">
            <div class="col-sm-10 ">
                <button type="submit" class="btn btn-primary">Add Author</button>
            </div>
        </div>


    </div>

</form>
<script
    src="https://code.jquery.com/jquery-3.4.1.min.js"
    integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
    crossorigin="anonymous"></script>

<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.1/jquery.validate.min.js"></script>

<script>
    $("#addAuthor").validate();
</script>
<script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/additional-methods.min.js"></script>
<script>
    // just for the demos, avoids form submit
    // jQuery.validator.setDefaults({
    //     debug: true,
    //     success: "valid"
    // });
    $( "#addAuthor" ).validate({
        rules: {
            fname: {
                required: true,
            },
            lname: {
                required: true
            },
            // dob: {
            //     required: true
            // },
            gender: {
                required: true
            },
            mobile: {
                required: true,
                digits: true,
                minlength: 10,
                maxlength: 10,
                exact

            },
            description: {
                required: true,

            },

        }
    });

</script> -->

@endsection

resources/views/author/deleteAuthor.blade.php
<form action="/lms/{{$author->id}}" method="post">
    @csrf
    @method('DELETE')



</form>

resources/views/author/displayAuthor.blade.php
@extends('html')

@section('title' , 'Display Author')
@section('js')
    <!-- Theme JS files -->

        <!-- <script type="text/javascript" src="assets/js/plugins/velocity/velocity.min.js"></script> -->
        <script type="text/javascript" src="assets/js/plugins/velocity/velocity.ui.min.js"></script>
        <script type="text/javascript" src="assets/js/plugins/buttons/spin.min.js"></script>
        <script type="text/javascript" src="assets/js/plugins/buttons/ladda.min.js"></script>
        <!-- <script type="text/javascript" src="assets/js/core/app.js"></script> -->
        <script type="text/javascript" src="assets/js/pages/components_buttons.js"></script>

        <script type="text/javascript" src="assets/js/plugins/ui/ripple.min.js"></script>
    <!-- /theme JS files -->
        <!-- Theme JS files -->
        <script type="text/javascript" src="assets/js/plugins/tables/datatables/datatables.min.js"></script>

        <!-- <script type="text/javascript" src="assets/js/pages/datatables_basic.js"></script> -->
@endsection
@section('content')



    <!-- <form action="" method="GET"> -->
        <table class="table datatable-basic mt-5">
            <thead>
            <tr>
                <th scope="col">First Name</th>
                <th scope="col">Last Name</th>
                <th scope="col">DOB</th>
                <th scope="col">Gender</th>
                <th scope="col">Mobile</th>
                <th scope="col">Description</th>
                <th class="text-center">Actions</th>
            </tr>
            </thead>
            <tbody>

            @foreach($authors as $author)
                <tr>
                    <td>{{ $author->fname }}</td>
                    <td>{{ $author->lname }}</td>
                    <td>{{ $author->dob }}</td>
                    <td>{{ $author->gender }}</td>
                    <td>{{ $author->mobile }}</td>
                    <td>{{ $author->author_description }}</td>
                    <td class="text-center">

{{--                        <form action="/lms/{{$author->id}}" method="POST">--}}
{{--                            @csrf--}}
{{--                            @method('DELETE')--}}

<a href="/lms/{{$author->id}}/edit"><i class="fas fa-edit mx-2"></i></a>
<a href=""  class="border-0 ml-2 deleteBtn" data-id="{{ $author->id }}" name="delete"><i class="fas fa-trash  mx-2"> </i> </a>
{{--<button class="border-0 ml-2 deleteBtn" type="submit" data-id="{{ $author->id }}" name="delete"><i class="fas fa-trash-alt"></i></button>--}}
                    </td>
{{--    </form>--}}
    </tr>
    @endforeach
    </tbody>
    </table>

    <b> {{ $authors->count() . " Records Found"}}</b>

    <!-- Colored button -->

    <form action="/lms/create" class="text-center">
        <button type="submit" class=" btn btn-primary btn-lg text-center">Add New Author</button>
    </form>

    <!-- </form> -->
@endsection


<script src="{{asset('js/jquery.js')}}"></script>
<script type="text/javascript" >

    $(document).ready(function(){
        $(".deleteBtn").click(function(){
            // alert('hello');
            let authorId = $(this).attr('data-id');

            var url = "{{ route('lms.destroy' , ['lm' => ':lmId'])}}";
            url = url.replace(':lmId', authorId);
            console.log('------',url);
            console.log(authorId);
            $.ajax({
                type:'POST',
                data:{_method: 'delete',_token : '{{ csrf_token() }}' },
                url: url,

                success: function() {
                    window.location.href = "{{ route('lms.index')}}";


                }


            });
        });
    });
</script>

resources/views/author/editAuthor.blade.php
@extends('html')



<link rel="stylesheet" href="https://jqueryvalidation.org/files/demo/site-demos.css">

@section('content')


<div class="row">
            <div class="col-md-8">

                <!-- Basic legend -->
                <form class="form-horizontal" action="/lms/{{$author->id}}" method="POST" id="editAuthor">
                @csrf
                @method('PUT')
                    <div class="panel panel-flat">
                        <div class="panel-heading">


                        </div>

                        <div class="panel-body">
                            <fieldset>
                                <legend class="text-semibold">Update Author Details</legend>

                                <div class="form-group">
                                    <label class="col-lg-3 control-label">First Name:</label>
                                    <div class="col-lg-9">
                                        <input type="text" class="form-control" name="fname" value="{{$author->fname}}">
                                    <div style="color: red"> @error('fname')
                                        {{$message}}
                                        @enderror
                                    </div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-lg-3 control-label">Last Name:</label>
                                    <div class="col-lg-9">
                                        <input type="text" class="form-control" name="lname" value="{{$author->lname}}">
                                    <div style="color: red"> @error('lname')
                                        {{$message}}
                                        @enderror
                                    </div>
                                    </div>
                                </div>

                                <div class="form-group">
										<label class="control-label col-lg-3">Date</label>
										<div class="col-lg-9">
                                            <input class="form-control" type="date" value="{{$author->dob}}" name="dob">
                                        <div style="color: red"> @error('dob')
                                            {{$message}}
                                            @enderror
                                        </div>
										</div>
									</div>

                                <!-- <div class="form-group ">
                                    <label class="col-lg-3 control-label">Date Of Birth</label>
                                    <div class="col-lg-9">
                                        <input type="text" class="form-control pickadate" name="dob" placeholder="Enter your Birthdate&hellip;">
                                    </div>
                                </div> -->

                                <div class="form-group">
                                    <label class="col-lg-3 control-label">Gender:</label>
                                    <div class="col-lg-9">
                                        <label class="radio-inline">
                                            <input type="radio" name="gender" class="styled" value="Male" {{$author->gender == 'Male' ? "Checked" : "" }}>
                                            Male
                                        </label>

                                        <label class="radio-inline">
                                            <input type="radio" name="gender" class="styled" value="Female" {{$author->gender == 'Female' ? "Checked" : "" }}>Female</label>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-lg-3 control-label">Contact Number:</label>
                                    <div class="col-lg-9">
                                        <input type="text" class="form-control" name="mobile" value="{{$author->mobile}}" placeholder="Contact Number">
                                    <div style="color: red"> @error('mobile')
                                        {{$message}}
                                        @enderror
                                    </div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-lg-3 control-label">Author Description:</label>
                                    <div class="col-lg-9">
                                        <textarea rows="5" cols="5" name="description" class="form-control">{{$author->author_description}}</textarea>
                                    <div style="color: red"> @error('description')
                                        {{$message}}
                                        @enderror
                                    </div>
                                    </div>
                                </div>
                            </fieldset>

                            <div class="text-right">
                                <button type="submit" class="btn btn-primary">Update Author <i class="icon-arrow-right14 position-right"></i></button>
                            </div>
                        </div>
                    </div>
                </form>
                <!-- /basic legend -->

            </div>
        </div>
<!-- old form -->
<!-- <form action="/lms/{{$author->id}}" method="POST" id="editAuthor">
    @csrf
    @method('PATCH')

    <div class="container mt-5">
        <h2>Update Author Details</h2>

        <div class="form-group row mt-5 ">
            <label for="" class="col-sm-2 col-form-label">First Name</label>
            <div class="col-sm-4">
                <input type="text" class="form-control" name="fname" placeholder="First Name" value="{{$author->fname}}">
            </div>
        </div>

        <div class="form-group row">
            <label for="" class="col-sm-2 col-form-label">Last Name</label>
            <div class="col-sm-4">
                <input type="text" class="form-control" name="lname" placeholder="Last Name" value="{{$author->lname}}">
            </div>
        </div>

        <div class="form-group row">
            <label for="" class="col-sm-2 col-form-label">DOB</label>
            <div class="col-sm-4">
                <input type="date" class="form-control" name="dob" placeholder="Last Name" value="{{$author->dob}}">
            </div>
        </div>


        <div class="form-group row">
            <label for="" class="col-sm-2 col-form-label">Gender</label>
            <div class="col-sm-4">
                <input type="radio" name="gender" value="Male" {{$author->gender == 'Male' ? "Checked" : "" }}> Male <br>
                <input type="radio" name="gender" value="Female" {{$author->gender == 'Female' ? "Checked" : "" }}> Female <br>
            </div>
        </div>

        <div class="form-group row">
            <label for="" class="col-sm-2 col-form-label">Mobile</label>
            <div class="col-sm-4">
                <input type="text" class="form-control" name="mobile" placeholder="Contact Number" value="{{$author->mobile}}">
            </div>
        </div>


        <div class="form-group row">
            <label for="" class="col-sm-2 col-form-label">Description</label>
            <div class="col-sm-4">
        <textarea name="description" class="form-control" id="" cols="30" rows="8">{{$author->author_description}}</textarea>
            </div>
        </div>


        <div class="form-group row">
            <div class="col-sm-10 ">
                <button type="submit" class="btn btn-primary">Update Author</button>
            </div>
        </div>


    </div>

</form> -->
<script src="https://code.jquery.com/jquery-1.11.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/jquery.validate.min.js"></script>
<script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/additional-methods.min.js"></script>
<script>
    // just for the demos, avoids form submit
    jQuery.validator.setDefaults({
        debug: true,
        success: "valid"
    });

    $( "#editAuthor" ).validate({
        submitHandler: function(form) {

        rules: {
            fname: {
                required: true
            },
            lname: {
                required: true
            },
            dob: {
                required: true
            },
            gender: {
                required: true
            },
            mobile: {
                required: true,
                digits: true,
                exactlength: 10,
            },
            description: {
                required: true,
            },
        }
        }
    });

</script>

@endsection